import { z } from "zod";

export const matchCreateSchema = z.object({
  homeTeamId: z.string().min(1, "Home team is required"),
  awayTeamId: z.string().min(1, "Away team is required"),
  homeClubId: z.string().optional().nullable(),
  awayClubId: z.string().optional().nullable(),
  matchDate: z.string().min(1, "Match date is required"),
  kickoffTime: z.string().optional().nullable(),
  seasonId: z.string().optional().nullable(),
  competitionId: z.string().optional().nullable(),
  venueId: z.string().optional().nullable(),
  matchDay: z.coerce.number().int().min(1).optional().nullable(),
  stage: z.string().optional().nullable(),
  status: z.enum(["SCHEDULED", "IN_PROGRESS", "COMPLETED", "POSTPONED", "CANCELLED", "ABANDONED"]).default("SCHEDULED"),
  homeScore: z.coerce.number().int().min(0).optional().nullable(),
  awayScore: z.coerce.number().int().min(0).optional().nullable(),
  homeHalfTimeScore: z.coerce.number().int().min(0).optional().nullable(),
  awayHalfTimeScore: z.coerce.number().int().min(0).optional().nullable(),
  homePenaltyScore: z.coerce.number().int().min(0).optional().nullable(),
  awayPenaltyScore: z.coerce.number().int().min(0).optional().nullable(),
  weather: z.string().optional().nullable(),
  pitchCondition: z.string().optional().nullable(),
  attendance: z.coerce.number().int().min(0).optional().nullable(),
  refereeName: z.string().optional().nullable(),
  notes: z.string().max(5000).optional().nullable(),
});

export const teamMatchStatsSchema = z.object({
  possession: z.coerce.number().min(0).max(100).optional().nullable(),
  totalPasses: z.coerce.number().int().min(0).optional().nullable(),
  accuratePasses: z.coerce.number().int().min(0).optional().nullable(),
  passAccuracy: z.coerce.number().min(0).max(100).optional().nullable(),
  shots: z.coerce.number().int().min(0).optional().nullable(),
  shotsOnTarget: z.coerce.number().int().min(0).optional().nullable(),
  shotsOffTarget: z.coerce.number().int().min(0).optional().nullable(),
  blockedShots: z.coerce.number().int().min(0).optional().nullable(),
  saves: z.coerce.number().int().min(0).optional().nullable(),
  corners: z.coerce.number().int().min(0).optional().nullable(),
  offsides: z.coerce.number().int().min(0).optional().nullable(),
  fouls: z.coerce.number().int().min(0).optional().nullable(),
  yellowCards: z.coerce.number().int().min(0).optional().nullable(),
  redCards: z.coerce.number().int().min(0).optional().nullable(),
  tackles: z.coerce.number().int().min(0).optional().nullable(),
  interceptions: z.coerce.number().int().min(0).optional().nullable(),
  clearances: z.coerce.number().int().min(0).optional().nullable(),
  duels: z.coerce.number().int().min(0).optional().nullable(),
  duelsWon: z.coerce.number().int().min(0).optional().nullable(),
  aerialDuels: z.coerce.number().int().min(0).optional().nullable(),
  aerialDuelsWon: z.coerce.number().int().min(0).optional().nullable(),
  dribbles: z.coerce.number().int().min(0).optional().nullable(),
  dribblesSuccessful: z.coerce.number().int().min(0).optional().nullable(),
  crosses: z.coerce.number().int().min(0).optional().nullable(),
  longBalls: z.coerce.number().int().min(0).optional().nullable(),
  freeKicks: z.coerce.number().int().min(0).optional().nullable(),
  throwIns: z.coerce.number().int().min(0).optional().nullable(),
  goalKicks: z.coerce.number().int().min(0).optional().nullable(),
  penaltiesAwarded: z.coerce.number().int().min(0).optional().nullable(),
  penaltiesScored: z.coerce.number().int().min(0).optional().nullable(),
  penaltiesMissed: z.coerce.number().int().min(0).optional().nullable(),
  ballRecoveries: z.coerce.number().int().min(0).optional().nullable(),
  turnovers: z.coerce.number().int().min(0).optional().nullable(),
  expectedGoals: z.coerce.number().min(0).optional().nullable(),
});

export const playerMatchStatsSchema = z.object({
  playerId: z.string().min(1, "Player is required"),
  teamId: z.string().optional().nullable(),
  starter: z.boolean().default(false),
  minutesPlayed: z.coerce.number().int().min(0).max(150).optional().nullable(),
  positionPlayed: z.string().optional().nullable(),
  jerseyNumber: z.coerce.number().int().min(1).max(99).optional().nullable(),
  isCaptain: z.boolean().default(false),
  subIn: z.coerce.number().int().min(0).optional().nullable(),
  subOut: z.coerce.number().int().min(0).optional().nullable(),
  goals: z.coerce.number().int().min(0).default(0),
  assists: z.coerce.number().int().min(0).default(0),
  ownGoals: z.coerce.number().int().min(0).default(0),
  shots: z.coerce.number().int().min(0).optional().nullable(),
  shotsOnTarget: z.coerce.number().int().min(0).optional().nullable(),
  passes: z.coerce.number().int().min(0).optional().nullable(),
  accuratePasses: z.coerce.number().int().min(0).optional().nullable(),
  keyPasses: z.coerce.number().int().min(0).optional().nullable(),
  tackles: z.coerce.number().int().min(0).optional().nullable(),
  interceptions: z.coerce.number().int().min(0).optional().nullable(),
  clearances: z.coerce.number().int().min(0).optional().nullable(),
  blocks: z.coerce.number().int().min(0).optional().nullable(),
  duelsWon: z.coerce.number().int().min(0).optional().nullable(),
  duelsLost: z.coerce.number().int().min(0).optional().nullable(),
  aerialDuelsWon: z.coerce.number().int().min(0).optional().nullable(),
  aerialDuelsLost: z.coerce.number().int().min(0).optional().nullable(),
  dribblesAttempted: z.coerce.number().int().min(0).optional().nullable(),
  dribblesCompleted: z.coerce.number().int().min(0).optional().nullable(),
  foulsCommitted: z.coerce.number().int().min(0).optional().nullable(),
  foulsSuffered: z.coerce.number().int().min(0).optional().nullable(),
  yellowCards: z.coerce.number().int().min(0).max(2).default(0),
  redCards: z.coerce.number().int().min(0).max(1).default(0),
  saves: z.coerce.number().int().min(0).optional().nullable(),
  goalsConceded: z.coerce.number().int().min(0).optional().nullable(),
  cleanSheet: z.boolean().optional().nullable(),
  penaltiesSaved: z.coerce.number().int().min(0).optional().nullable(),
  rating: z.coerce.number().min(1).max(10).optional().nullable(),
  coachNotes: z.string().max(2000).optional().nullable(),
  injuryDuringMatch: z.boolean().default(false),
});

export const matchEventSchema = z.object({
  matchId: z.string().min(1),
  playerId: z.string().optional().nullable(),
  type: z.enum([
    "GOAL", "OWN_GOAL", "ASSIST", "YELLOW_CARD", "RED_CARD", "SECOND_YELLOW",
    "SUBSTITUTION_IN", "SUBSTITUTION_OUT", "PENALTY_SCORED", "PENALTY_MISSED",
    "INJURY", "VAR_DECISION",
  ]),
  minute: z.coerce.number().int().min(0).max(150),
  addedTime: z.coerce.number().int().min(0).optional().nullable(),
  half: z.enum(["FIRST_HALF", "SECOND_HALF", "EXTRA_TIME_1", "EXTRA_TIME_2", "PENALTY_SHOOTOUT"]).optional().nullable(),
  teamSide: z.enum(["HOME", "AWAY"]).optional().nullable(),
  description: z.string().max(500).optional().nullable(),
  relatedPlayerId: z.string().optional().nullable(),
});

export type MatchCreateInput = z.infer<typeof matchCreateSchema>;
export type TeamMatchStatsInput = z.infer<typeof teamMatchStatsSchema>;
export type PlayerMatchStatsInput = z.infer<typeof playerMatchStatsSchema>;
export type MatchEventInput = z.infer<typeof matchEventSchema>;
